version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - gfortran
    - cmake

python:
  install:
    - requirements: docs/pre-requirements.txt
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py