"""
wrfrun.res
##########

This module contains resources used by other wrfrun modules.

A ``__init__.py`` file will be generated by ``generate_init.py`` when building the package.

The main resource directory and each subdirectory has a ``name_map.json`` file,
which maps real name of files or directories to a simpler name.
``generate_init.py`` reads these JSON and generates variable names based on the name inside it.

For example, assume we have a directory which structure is like:

.. code-block::

    res
     |
     |---extension
     |      |
     |      |---plotgrids.ncl
     |      ----name_map.json
     |
     |---job_scheduler
     |      |
     |      |---pbs.template
     |      ----name_map.json
     |
     |---config.yaml.template
     ----name_map.json

And the content of each ``name_map.json`` is:

.. code-block:: json
    :caption: name_map.json

    {
        "extension": {
            "name": "EXT",
            "type": "dir",
        },
        "job_scheduler": {
            "name": "JOBSYS",
            "type": "dir",
        },
        "config.yaml.template": {
            "name": "CONFIG_TEMPLATE",
            "type": "file",
        }
    }

.. code-block:: json
    :caption: name_map.json

    {
        "plotgrids.ncl": {
            "name": "PLOT_DOMAIN_NCL",
            "type": "file",
        }
    }

.. code-block:: json
    :caption: name_map.json

    {
        "pbs.template": {
            "name": "PBS_TEMPLATE",
            "type": "file",
        }
    }

Then, the generated variable names in ``__init__.py`` are:

.. code-block:: python
    :caption: __init__.py

    EXT_PLOT_DOMAIN_NCL = "..."
    JOBSYS_PBS_TEMPLATE = "..."
    CONFIG_TEMPLATE = "..."
"""

# This file is generated by scripts `wrfrun/res/generate_init.py`.
# Don't change this file directly.

from os.path import abspath, dirname

from wrfrun.core import WRFRUN, WRFRunConfig

RES_PATH = abspath(dirname(__file__))


def _register_res_uri(wrfrun_config: WRFRunConfig):
    wrfrun_config.register_resource_uri(wrfrun_config.WRFRUN_RESOURCE_PATH, RES_PATH)


WRFRUN.set_config_register_func(_register_res_uri)


RUN_SH_TEMPLATE = ":WRFRUN_RESOURCE_PATH:/run.template.sh"
GITIGNORE_RULES = ":WRFRUN_RESOURCE_PATH:/gitignore.rules"
EXT_NCL_PLOT_SCRIPT = ":WRFRUN_RESOURCE_PATH:/extension/plotgrids.ncl"
SCHEDULER_LSF_TEMPLATE = ":WRFRUN_RESOURCE_PATH:/scheduler/lsf.template"
SCHEDULER_PBS_TEMPLATE = ":WRFRUN_RESOURCE_PATH:/scheduler/pbs.template"
SCHEDULER_SLURM_TEMPLATE = ":WRFRUN_RESOURCE_PATH:/scheduler/slurm.template"
NAMELIST_WRFDA = ":WRFRUN_RESOURCE_PATH:/namelist/namelist.input.da_wrfvar.template"
NAMELIST_DFI = ":WRFRUN_RESOURCE_PATH:/namelist/namelist.input.dfi.template"
NAMELIST_REAL = ":WRFRUN_RESOURCE_PATH:/namelist/namelist.input.real.template"
NAMELIST_WRF = ":WRFRUN_RESOURCE_PATH:/namelist/namelist.input.wrf.template"
NAMELIST_WPS = ":WRFRUN_RESOURCE_PATH:/namelist/namelist.wps.template"
CONFIG_MAIN_TOML_TEMPLATE = ":WRFRUN_RESOURCE_PATH:/config/config.template.toml"
CONFIG_WRF_TOML_TEMPLATE = ":WRFRUN_RESOURCE_PATH:/config/wrf.template.toml"
CONFIG_PALM_TOML_TEMPLATE = ":WRFRUN_RESOURCE_PATH:/config/palm.template.toml"


def _set_config_template_path(wrfrun_config: WRFRunConfig):
    wrfrun_config.set_config_template_path(CONFIG_MAIN_TOML_TEMPLATE)


WRFRUN.set_config_register_func(_set_config_template_path)


__all__ = [
    "RUN_SH_TEMPLATE",
    "GITIGNORE_RULES",
    "EXT_NCL_PLOT_SCRIPT",
    "SCHEDULER_LSF_TEMPLATE",
    "SCHEDULER_PBS_TEMPLATE",
    "SCHEDULER_SLURM_TEMPLATE",
    "NAMELIST_WRFDA",
    "NAMELIST_DFI",
    "NAMELIST_REAL",
    "NAMELIST_WRF",
    "NAMELIST_WPS",
    "CONFIG_MAIN_TOML_TEMPLATE",
    "CONFIG_WRF_TOML_TEMPLATE",
    "CONFIG_PALM_TOML_TEMPLATE",
]
