"""
wrfrun.res
##########

This module contains resources used by other wrfrun modules.

A ``__init__.py`` file will be generated by ``generate_init.py`` when building the package.

The main resource directory and each subdirectory has a ``name_map.json`` file,
which maps real name of files or directories to a simpler name.
``generate_init.py`` reads these JSON and generates variable names based on the name inside it.

For example, assume we have a directory which structure is like:

.. code-block::

    res
     |
     |---extension
     |      |
     |      |---plotgrids.ncl
     |      ----name_map.json
     |
     |---job_scheduler
     |      |
     |      |---pbs.template
     |      ----name_map.json
     |
     |---config.yaml.template
     ----name_map.json

And the content of each ``name_map.json`` is:

.. code-block:: json
    :caption: name_map.json

    {
        "extension": {
            "name": "EXT",
            "type": "dir",
        },
        "job_scheduler": {
            "name": "JOBSYS",
            "type": "dir",
        },
        "config.yaml.template": {
            "name": "CONFIG_TEMPLATE",
            "type": "file",
        }
    }

.. code-block:: json
    :caption: name_map.json

    {
        "plotgrids.ncl": {
            "name": "PLOT_DOMAIN_NCL",
            "type": "file",
        }
    }

.. code-block:: json
    :caption: name_map.json

    {
        "pbs.template": {
            "name": "PBS_TEMPLATE",
            "type": "file",
        }
    }

Then, the generated variable names in ``__init__.py`` are:

.. code-block:: python
    :caption: __init__.py

    EXT_PLOT_DOMAIN_NCL = "..."
    JOBSYS_PBS_TEMPLATE = "..."
    CONFIG_TEMPLATE = "..."
"""

# This file is generated by scripts `wrfrun/res/generate_init.py`.
# Don't change this file directly.

from wrfrun.core import ResourceRef

RUN_SH_TEMPLATE = ResourceRef("core", "run.template.sh")
GITIGNORE_RULES = ResourceRef("core", "gitignore.rules")
EXT_NCL_PLOT_SCRIPT = ResourceRef("core", "extension/plotgrids.ncl")
SCHEDULER_LSF_TEMPLATE = ResourceRef("core", "scheduler/lsf.template")
SCHEDULER_PBS_TEMPLATE = ResourceRef("core", "scheduler/pbs.template")
SCHEDULER_SLURM_TEMPLATE = ResourceRef("core", "scheduler/slurm.template")
NAMELIST_WRFDA = ResourceRef("core", "namelist/namelist.input.da_wrfvar.template")
NAMELIST_DFI = ResourceRef("core", "namelist/namelist.input.dfi.template")
NAMELIST_REAL = ResourceRef("core", "namelist/namelist.input.real.template")
NAMELIST_WRF = ResourceRef("core", "namelist/namelist.input.wrf.template")
NAMELIST_WPS = ResourceRef("core", "namelist/namelist.wps.template")
CONFIG_ARPS_TOML_TEMPLATE = ResourceRef("core", "config/arps.template.toml")
CONFIG_MAIN_TOML_TEMPLATE = ResourceRef("core", "config/config.template.toml")
CONFIG_WRF_TOML_TEMPLATE = ResourceRef("core", "config/wrf.template.toml")
CONFIG_PALM_TOML_TEMPLATE = ResourceRef("core", "config/palm.template.toml")
CONFIG_ROMS_TOML_TEMPLATE = ResourceRef("core", "config/roms.template.toml")


__all__ = [
    "RUN_SH_TEMPLATE",
    "GITIGNORE_RULES",
    "EXT_NCL_PLOT_SCRIPT",
    "SCHEDULER_LSF_TEMPLATE",
    "SCHEDULER_PBS_TEMPLATE",
    "SCHEDULER_SLURM_TEMPLATE",
    "NAMELIST_WRFDA",
    "NAMELIST_DFI",
    "NAMELIST_REAL",
    "NAMELIST_WRF",
    "NAMELIST_WPS",
    "CONFIG_ARPS_TOML_TEMPLATE",
    "CONFIG_MAIN_TOML_TEMPLATE",
    "CONFIG_WRF_TOML_TEMPLATE",
    "CONFIG_PALM_TOML_TEMPLATE",
    "CONFIG_ROMS_TOML_TEMPLATE",
]
