# Submodels' config of ARPS are splited into multiple blocks.

# Global configs
[global]
# For example, /home/syize/Apps/ARPS/bin
arps_bin_directory = "/path/to/your/ARPS/binary/folder"
# Namelist for arps core and some arps' submodule.
user_namelist = "/path/to/the/namelist"

# Grid settings
grid_nx = 42
grid_dx = 30000.0
grid_ny = 38
grid_dy = 30000.0
grid_nz = 53
grid_dz = 500.0
grid_center_latitude = 31.971
grid_center_longitude = 118.784
# # Vertical stretching settings
# # Minimum vertical grid spacing 
grid_min_dz = 50.0
# # The height of the bottom level of the grid.
grid_z_bottom_height = 10.0
# # The height above which the stretch will be applied.
grid_z_stretch_start_height = 3000.0
# # The height above which the stretch will be stopped.
grid_z_stretch_end_height = 1.0e5
# # The height above which the grid will start to become 
# # flat in terrain-following coordinate transformation.
grid_z_start_flat_height = 20000.0
# Supported projection:
# - "": no projection
# - "polar": Polar projection, wrfrun will determine its type (north or south) based on your grid_center_latitude
# - "lambert": Lambert projection, wrfrun will determine its type (north or south) based on your grid_center_latitude
# - "mercator": Mercator projection.
grid_projection = "lambert"
grid_projection_true_lat_1 = 31.971
grid_projection_true_lat_2 = 31.971
grid_projection_true_lon = 118.784

# Integrate settings, unit: seconds
integrate_large_time_step = 6.0

is_restart = false

# ########################## Config for submodels ##############################
# NOTE:
#     wrfrun will mark if the submodel is available by add new value at runtime:
#
#     is_valid = True / False
#
#     Because it is annoying to set `is_valid` manually for each submodel.
#     wrfrun will detect if submodel's binary exists, mark it as `True` or `False`,
#     and warn the user in logs.
#     If you believe wrfrun makes a mistake, you can manually change the value
#     of `is_valid` in ARPS model config, for example:
#
#     WRFRUN.config.update_model_config("arps", {"arpstrn": {"is_valid": True}})

# Config for arpssfc
[arpssfc]

# Config for arpstrn
[arpstrn]
# For example, /share/ARPS/terrain/arpstopo30.data
dir_terrain_data = "/path/to/your/terrain/base/data/folder"
user_namelist = "/path/to/the/namelist/for/arpstrn"

# Config for ext2arps
[ext2arps]

# Config for arps3dvar
[arps3dvar]

# Config for arpsintrp
[arpsintrp]
# Its base namelist is templates/arps/arpsintrp.nml. Place optional updates in
# namelists/arps/arpsintrp.nml.

# Config for arps
[arps]

# ##############################################################################
