"""
wrfrun.cli
##########

.. autosummary::
    :toctree: generated/

    main_entry

``wrfrun`` command line interface (CLI).

**This is an experimental tool, NOT BEING STABLE YET.**

After installing ``wrfrun``, you can use command ``wrfrun`` to create a simulation project.
Get more information by running ``wrfrun --help``.
"""

import argparse
import sys
from os import listdir
from pathlib import Path

import tomli
import tomli_w

from .core import WRFRUN_NEW, create_wrfrun_session
from .log import logger
from .res import (
    CONFIG_ARPS_TOML_TEMPLATE,
    CONFIG_MAIN_TOML_TEMPLATE,
    CONFIG_PALM_TOML_TEMPLATE,
    CONFIG_ROMS_TOML_TEMPLATE,
    CONFIG_WRF_TOML_TEMPLATE,
    GITIGNORE_RULES,
)

MODEL_MAP = {
    "arps": CONFIG_ARPS_TOML_TEMPLATE,
    "wrf": CONFIG_WRF_TOML_TEMPLATE,
    "palm": CONFIG_PALM_TOML_TEMPLATE,
    "roms": CONFIG_ROMS_TOML_TEMPLATE,
}

CLI_SESSION = create_wrfrun_session("./wrfrun")


def _entry_init(args: argparse.Namespace):
    """
    Initialize a wrfrun project.

    :param args: Arguments namespace.
    :type args: argparse.Namespace
    """
    configs = vars(args)

    project_path = Path(configs["path"]).resolve()
    models = configs["models"]

    if project_path.is_dir():
        # we need to check if this directory isn't empty.
        files = listdir()
        # exclude:
        exclude_target = [
            ".venv",
            ".git",
            ".gitattribute",
            ".python-version",
            "pyproject.toml",
            "uv.lock",
            "configs",
            "data",
            "namelists",
            "config.toml",
        ]
        files = [x for x in files if x not in exclude_target]

        if len(files) != 0:
            logger.error(f"[CLI] {project_path} isn't empty, choose an empty directory, or backup and delete your files first.")
            exit(1)

    for _path in [
        project_path / "configs",
        project_path / "data",
        project_path / "outputs",
        project_path / "namelists",
        project_path / "templates",
    ]:
        _path.mkdir(exist_ok=True, parents=True)

    WRFRUN_NEW.io.copy(file_path=CONFIG_MAIN_TOML_TEMPLATE, save_path=project_path / "config.toml")
    WRFRUN_NEW.io.copy(file_path=GITIGNORE_RULES, save_path=project_path / ".gitignore")

    model_list = []
    if models is not None:
        for _model in models:
            if _model in MODEL_MAP:
                WRFRUN_NEW.io.copy(file_path=MODEL_MAP[_model], save_path=project_path / f"configs/{_model}.toml")
                (project_path / f"namelists/{_model}").mkdir(exist_ok=True)
                (project_path / f"data/{_model}").mkdir(exist_ok=True)
                (project_path / f"templates/{_model}").mkdir(exist_ok=True)
                model_list.append(_model)

            else:
                logger.warning(f"Unknown model: '{_model}'")

    logger.info(f"Created project {project_path}.")
    if len(model_list) > 0:
        logger.info(f"Use the following models: {model_list}.")
    logger.info(f"All your configs should be placed in '{project_path}/configs'.")
    logger.info(f"All your data should be placed in '{project_path}/data'.")
    logger.info(f"All your namelist template files should be placed in '{project_path}/templates'")
    logger.info(f"All your namelist files should be placed in '{project_path}/namelists'")
    logger.info(f"Make sure to set `[magenta]use = True[/]` to enable models in '{project_path}/config.toml' .")
    logger.info("It is recommanded to use git to track your wrfrun and model configs.")
    logger.info("Use command `[magenta]wrfrun add MODEL_NAME[/]` to add a new model to project.")


def _entry_model(args: argparse.Namespace):
    """
    Manage models used by wrfrun project.

    :param args: Arguments namespace.
    :type args: argparse.Namespace
    """
    configs = vars(args)
    new_models = configs["add"]
    config_path = Path(configs["config"]).resolve()
    project_path = config_path.parent

    if not config_path.is_file():
        logger.error(f"Can't find '{config_path}', initialize this project first.")
        exit(1)

    for _new_model in new_models:
        if _new_model not in MODEL_MAP:
            logger.error(f"Unknow model type: '{_new_model}'")
            exit(1)

    config_dir_path = config_path.parent / "configs"
    config_dir_path.mkdir(exist_ok=True, parents=True)

    with open(config_path, "rb") as f:
        main_config = tomli.load(f)

    for _new_model in new_models:
        if _new_model not in main_config["model"]:
            main_config["model"][_new_model] = {
                "note": (
                    "Config of this model is generated by wrfrun cli command. "
                    "DO NOT ADD CUSTOM CONFIG IN THIS SECTION because they may be overwrite by wrfrun cli tools."
                ),
                "use": True,
                "include": f"./configs/{_new_model}.toml",
            }

        else:
            if not ("use" in main_config["model"] and main_config["model"]["use"]):
                main_config["model"][_new_model] = {
                    "note": (
                        "Config of this model is generated by wrfrun cli command. "
                        "DO NOT ADD CUSTOM CONFIG IN THIS SECTION because they may be overwrite by wrfrun cli tools."
                    ),
                    "use": True,
                    "include": f"./configs/{_new_model}.toml",
                }

    for _new_model in new_models:
        WRFRUN_NEW.io.copy(file_path=MODEL_MAP[_new_model], save_path=config_dir_path / f"{_new_model}.toml")
        (project_path / f"namelists/{_new_model}").mkdir(exist_ok=True)
        (project_path / f"data/{_new_model}").mkdir(exist_ok=True)
        (project_path / f"templates/{_new_model}").mkdir(exist_ok=True)

    with open(config_path, "wb") as f:
        tomli_w.dump(main_config, f)

    logger.info(f"Added models: {new_models}")


def main_entry():
    """
    CLI entry point.
    """
    args_parser = argparse.ArgumentParser()
    subparsers = args_parser.add_subparsers(title="Subcommands", description="Valid Subcommands", help="Subcommands")

    init_parser = subparsers.add_parser("init", help="Initialize a wrfrun project.", add_help=True)
    init_parser.add_argument("-p", "--path", type=str, default=".", help="Path of the wrfrun project.")
    init_parser.add_argument(
        "--models",
        nargs="*",
        type=str,
        help="List of models to use.",
        choices=["wrf", "palm", "roms", "arps"],
    )
    init_parser.set_defaults(func=_entry_init)

    model_parser = subparsers.add_parser("model", help="Manage models used by wrfrun project.", add_help=True)
    model_parser.add_argument("-c", "--config", type=str, default="config.toml", help="Path of the main config file.")
    model_parser.add_argument(
        "-a",
        "--add",
        nargs="+",
        required=True,
        type=str,
        help="Add models to the project.",
        choices=["wrf", "palm", "roms", "arps"],
    )
    model_parser.set_defaults(func=_entry_model)

    args = args_parser.parse_args(args=None if sys.argv[1:] else ["--help"])
    args.func(args)


__all__ = ["main_entry"]
