"""
wrfrun.cli
##########

.. autosummary::
    :toctree: generated/

    main_entry

``wrfrun`` command line interface (CLI).

**This is an experimental tool, NOT BEING STABLE YET.**

After installing ``wrfrun``, you can use command ``wrfrun`` to create a simulation project.
Get more information by running ``wrfrun --help``.
"""

import argparse
import sys
from os import listdir, makedirs
from os.path import abspath, dirname, exists
from shutil import copyfile

import tomli
import tomli_w

from .core import WRFRunConfig
from .log import logger
from .res import (
    CONFIG_MAIN_TOML_TEMPLATE,
    CONFIG_PALM_TOML_TEMPLATE,
    CONFIG_WRF_TOML_TEMPLATE,
    GITIGNORE_RULES,
    _register_res_uri,
)

MODEL_MAP = {
    "wrf": CONFIG_WRF_TOML_TEMPLATE,
    "palm": CONFIG_PALM_TOML_TEMPLATE,
}

# need some mannual calls to make cli work without a config file.
wrfrun_config = WRFRunConfig("./.wrfrun")
_register_res_uri(wrfrun_config)


def _entry_init(args: argparse.Namespace):
    """
    Initialize a wrfrun project.

    :param args: Arguments namespace.
    :type args: argparse.Namespace
    """
    configs = vars(args)

    project_name = configs["name"]
    models = configs["models"]

    if project_name is None:
        project_name = "."

    if exists(project_name):
        # we need to check if this directory isn't empty.
        files = listdir()
        # exclude:
        exclude_target = [
            ".venv",
            ".git",
            ".gitattribute",
            "pyproject.toml",
            "uv.lock",
            "configs",
            "data",
            "namelists",
            "config.toml",
        ]
        files = [x for x in files if x not in exclude_target]

        if len(files) != 0:
            logger.error(f"[CLI] {project_name} isn't empty, choose an empty directory, or backup and delete your files first.")
            exit(1)

    makedirs(f"{project_name}/configs")
    makedirs(f"{project_name}/data")
    namelist_path = f"{project_name}/namelists"
    makedirs(namelist_path)

    copyfile(wrfrun_config.parse_resource_uri(CONFIG_MAIN_TOML_TEMPLATE), f"{project_name}/config.toml")
    copyfile(wrfrun_config.parse_resource_uri(GITIGNORE_RULES), f"{project_name}/.gitignore")

    model_list = []
    if models is not None:
        for _model in models:
            if _model in MODEL_MAP:
                src_path = wrfrun_config.parse_resource_uri(MODEL_MAP[_model])
                copyfile(src_path, f"{project_name}/configs/{_model}.toml")
                makedirs(f"{namelist_path}/{_model}")
                model_list.append(_model)

            else:
                logger.warning(f"Unknown model: '{_model}'")

    logger.info(f"Created project {project_name}.")
    if len(model_list) > 0:
        logger.info(f"Use the following models: {model_list}.")
    logger.info(f"All your configs should be placed in '{project_name}/configs'.")
    logger.info(f"All your data should be placed in '{project_name}/data'.")
    logger.info(f"All your namelist files should be placed in '{namelist_path}'")
    logger.info(f"Make sure to set `[magenta]use = True[/]` to enable models in '{project_name}/config.toml' .")
    logger.info("It is recommanded to use git to track your wrfrun and model configs.")
    logger.info("Use command `[magenta]wrfrun add MODEL_NAME[/]` to add a new model to project.")


def _entry_model(args: argparse.Namespace):
    """
    Manage models used by wrfrun project.

    :param args: Arguments namespace.
    :type args: argparse.Namespace
    """
    configs = vars(args)
    new_models = configs["add"]
    config_path = configs["config"]

    if not exists(config_path):
        logger.error(f"Can't find '{config_path}', initialize this project first.")
        exit(1)

    for _new_model in new_models:
        if _new_model not in MODEL_MAP:
            logger.error(f"Unknow model type: '{_new_model}'")
            exit(1)

    config_dir_path = f"{abspath(dirname(config_path))}/configs"

    if not exists(config_dir_path):
        makedirs(config_dir_path)

    with open(config_path, "rb") as f:
        main_config = tomli.load(f)

    for _new_model in new_models:
        if _new_model not in main_config["model"]:
            main_config["model"][_new_model] = {
                "note": (
                    "Config of this model is generated by wrfrun cli command. "
                    "DO NOT ADD CUSTOM CONFIG IN THIS SECTION because they may be overwrite by wrfrun cli tools."
                ),
                "use": True,
                "include": f"./configs/{_new_model}.toml",
            }

        else:
            if not ("use" in main_config["model"] and main_config["model"]["use"]):
                main_config["model"][_new_model] = {
                    "note": (
                        "Config of this model is generated by wrfrun cli command. "
                        "DO NOT ADD CUSTOM CONFIG IN THIS SECTION because they may be overwrite by wrfrun cli tools."
                    ),
                    "use": True,
                    "include": f"./configs/{_new_model}.toml",
                }

    for _new_model in new_models:
        copyfile(wrfrun_config.parse_resource_uri(MODEL_MAP[_new_model]), f"{config_dir_path}/{_new_model}.toml")

    with open(config_path, "wb") as f:
        tomli_w.dump(main_config, f)

    logger.info(f"Added models: {new_models}")


def main_entry():
    """
    CLI entry point.
    """
    args_parser = argparse.ArgumentParser()
    subparsers = args_parser.add_subparsers(title="Subcommands", description="Valid Subcommands", help="Subcommands")

    init_parser = subparsers.add_parser("init", help="Initialize a wrfrun project.", add_help=True)
    init_parser.add_argument("-n", "--name", type=str, help="Name of the wrfrun project.")
    init_parser.add_argument("--models", nargs="*", type=str, help="List of models to use.", choices=["wrf", "palm"])
    init_parser.set_defaults(func=_entry_init)

    model_parser = subparsers.add_parser("model", help="Manage models used by wrfrun project.", add_help=True)
    model_parser.add_argument("-c", "--config", type=str, default="config.toml", help="Path of the main config file.")
    model_parser.add_argument(
        "-a", "--add", nargs="+", required=True, type=str, help="Add models to the project.", choices=["wrf", "palm"]
    )
    model_parser.set_defaults(func=_entry_model)

    args = args_parser.parse_args(args=None if sys.argv[1:] else ["--help"])
    args.func(args)


__all__ = ["main_entry"]
